add manjaro nibia installer

diff --git a/inc-functions b/inc-functions
--- a/inc-functions
+++ b/inc-functions
@@ -202,6 +202,13 @@ __function_common() {
 		[[ -e "${1}" || -h "${1}" ]] && _evalq mv "${1}" "${1}.keep$(date +%s)"
 	}
 
+	_keepcpts_rt() {
+		[[ -e "${1}" || -h "${1}" ]] && _evalq sudo cp -a "${1}" "${1}.keep$(date +%s)"
+	}
+	_keepmvts_rt() {
+		[[ -e "${1}" || -h "${1}" ]] && _evalq sudo mv "${1}" "${1}.keep$(date +%s)"
+	}
+
 	##############  PWD
 
 	_pwd() { < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c14; }
@@ -573,8 +580,8 @@ __data() {
 	_IPS_AUTH=`printf "%q\n" ${S_IPS_ADMIN} ${S_IPS_DEV} | sort -u | xargs`
 
 	# server type
-	[ ${S_SERVER_TYPE} != 'vz' ] && _IPTHIS=`_get_ip` || _IPTHIS=`_get_ip ${S_ETH}`
-	[ ${S_SERVER_TYPE} != 'vz' ] && _IPTHISV6=`_get_ipv6`
+	[ "${S_SERVER_TYPE}" != 'vz' ] && _IPTHIS=`_get_ip` || _IPTHIS=`_get_ip ${S_ETH}`
+	[ "${S_SERVER_TYPE}" != 'vz' ] && _IPTHISV6=`_get_ipv6`
 
 	# IPs
 	if [[ " lxc vz docker " = *" $S_SERVER_TYPE "* ]]; then
@@ -595,6 +602,12 @@ if [ -z $S_INC_FUNCTIONS ]; then
 	# global configuration
 	S_GLOBAL_CONF="${S_GLOBAL_CONF:-/etc/server/server.conf}"
 	! . "$S_GLOBAL_CONF" && echo -e "[error] - Unable to source file '$S_GLOBAL_CONF' from '${BASH_SOURCE[0]}'" && echo 1
+
+	# initialize configuration
+	#file="${_PATH_BASE}/conf-init.install"
+	#if ! . "$file"; then
+	#	echo -e "[error] - unable to find file '$file' from ${BASH_SOURCE[0]}" && exit 1
+	#fi
 
 	# init functions
 	__function_common
diff --git a/old/sub/lysia-btrfs1.install b/old/sub/lysia-btrfs1.install
--- a/old/sub/lysia-btrfs1.install
+++ b/old/sub/lysia-btrfs1.install
@@ -3,20 +3,68 @@
 # write by Aguy
 
 _path_base=`dirname "$(readlink -e "$0")"`
-file=`readlink -e "${_path_base}/../inc-functions"`
-if [ -f "$file" ]; then . "$file"; else echo -e "\e[0;31merror - unable to load file '${file}' from ${BASH_SOURCE[0]}${cclear}\e[0;0m" && exit 0; fi
+#file=`readlink -e "${_path_base}/../inc-functions"`
+#if [ -f "$file" ]; then . "$file"; else echo -e "\e[0;31merror - unable to load file '${file}' from ${BASH_SOURCE[0]}${cclear}\e[0;0m" && exit 0; fi
 
 _PATH_LOG="/var/log/server/install"
-S_FILE_INSTALL_CONF="${S_PATH_CONF}/install.conf"
-S_FILE_INSTALL_DONE="${S_PATH_CONF}/install.done"
-
-########################################  MAIN
+_PATH_CONF="/etc/server"
+_FILE_INSTALL_CONF="${_PATH_CONF}/install.conf"
+_FILE_INSTALL_DONE="${_PATH_CONF}/install.done"
 
 _PART="btrfs1"
 
+! [ -d "${_PATH_CONF}" ] && mkdir -p "${_PATH_CONF}/ssl"
+
+########################################  FUNCTIONS
+
+# colors
+white='\e[0;0m'; red='\e[0;31m'; green='\e[0;32m'; blue='\e[0;34m'; magenta='\e[0;35m'; yellow='\e[0;33m'
+whiteb='\e[1;1m'; redb='\e[1;31m'; greenb='\e[1;32m'; blueb='\e[1;34m'; magentab='\e[1;35m'; yellowb='\e[1;33m'; cclear='\e[0;0m'
+
+_echoi() { echo -e "${yellow}${*}${cclear}"; }
+_echoI() { echo -e "${yellowb}${*}${cclear}"; }
+_echoT() { echo -e "${blueb}${*}${cclear}"; }
+_askno() { _ANSWER=; echo -en "$*: "; read _ANSWER; }
+_askyn() {
+	_ANSWER=
+	options=" y n "
+	while [ "${options/ $_ANSWER }" = "$options" ]; do
+		echo -e -n "$* y/n: "
+		read _ANSWER
+	done
+}
+_menu() {
+	PS3="$1: "
+	shift
+	select _ANSWER in $*
+		do [ "$_ANSWER" ] && break || echo -e "\nTry again"
+	done
+}
+_parthave() { [ -f "$2" ] && grep -q "^$1$" "$2" || (touch "$2"; return 1); }
+_partadd() { ! _parthave "$1" "$2" && echo "$1" >> "$2" || return 0; }
+_confhave() {
+	local file
+	file="${2:-$_FILE_INSTALL_CONF}"
+	! [ -f "$file" ] && _exite "unable to find '$file' from $FUNCNAME"
+	grep -q "^$1=.*" "$file"
+}
+_confset() {
+	local file
+	file="${3:-$_FILE_INSTALL_CONF}"
+	! [ -f "$file" ] && touch "$file"
+
+	if _confhave "$1" "$file"; then
+		sed -i "\|^$1=| c${1}=${2:+\"$2\"}" "$file"
+	else
+		echo "${1}=${2:+\"$2\"}" >> "$file"
+	fi
+}
+
+########################################  MAIN
+
 # exit
 [ "$USER" != root ] && _echoE "You have to run this script under root privileges" && exit 1
-[ -f "${S_FILE_INSTALL_DONE}" ] && _parthave "${_PART}" "${S_FILE_INSTALL_DONE}" && _echoi "performed *** ${_PART}" && exit 0
+[ -f "${_FILE_INSTALL_DONE}" ] && _parthave "${_PART}" "${_FILE_INSTALL_DONE}" && _echoi "performed *** ${_PART}" && exit 0
 
 [ ! -d ${_PATH_LOG} ] && mkdir -p ${_PATH_LOG}
 
@@ -29,11 +77,14 @@ _askyn "This part have to be launched after installation and BEFORE reboot\nConf
 
 _echoT "------------------ Data"
 
-[ -z ${_UEFI+x} ] && echo -e "${yellow}$(blkid|grep -v /loop)${cclear}" && _askno "If UEFI are enabled, give partition name for UEFI" && _UEFI=${_ANSWER:-$anstmp}
+lsblk -e 11,7 -o name,size,mountpoint
+echo -e "\n${yellow}$(blkid|grep -v /loop)${cclear}"
+
+[ -z ${_UEFI+x} ] && _askno "If UEFI are enabled, give partition name for UEFI" && _UEFI=${_ANSWER:-$anstmp}
 _confset _UEFI "$_UEFI"
 
-[ -z ${_USERNAME+x} ] && _menu "Select a user name" nikita manjaro lysia $USER && _USERNAME="$_ANSWER"
-_confset _USERNAME "${_USERNAME}"
+[ -z ${_USERNAME+x} ] && anstmp="nikita" && _askno "Select a user name (${anstmp})" && _USERNAME=${_ANSWER:-$anstmp}
+_confset _USERNAME "$_USERNAME"
 
 [ -z ${_DEVICE_SYS+x} ] && _menu "Select a device for system installation" $(blkid -o device|grep -v '/loop'|xargs) && _DEVICE_SYS=$_ANSWER
 _confset _DEVICE_SYS "${_DEVICE_SYS}"
@@ -41,14 +92,14 @@ _confset _DEVICE_SYS "${_DEVICE_SYS}"
 [ -z ${_SYSNAME+x} ] && anstmp=lysia && _askno "Give a prefix/sufix btrfs volume name for system device '${_DEVICE_SYS}' ($anstmp)" && _SYSNAME=${_ANSWER:-$anstmp}
 _confset _SYSNAME "${_SYSNAME}"
 
-[ -z ${_DEVICE_EXT+x} ] && lsblk -e 11,7 -o name,size,mountpoint && anstmp='' && _askno "Give a device for 'extend' device if exists ($anstmp)" && _DEVICE_EXT=${_ANSWER:-$anstmp}
+[ -z ${_DEVICE_EXT+x} ] && anstmp="" && _askno "Give a device for 'extend' device if exists ($anstmp)" && _DEVICE_EXT=${_ANSWER:-$anstmp}
 _confset _DEVICE_EXT "$_DEVICE_EXT"
 
-[ -z ${_DEVICE_GRUB+x} ] && lsblk -e 11,7 -o name,size,mountpoint && anstmp='/dev/sda' && _askno "Give a device for grub installation" "$(blkid -o device|grep -v '/loop'|xargs) ($anstmp)" && _DEVICE_GRUB=${_ANSWER:-$anstmp}
+[ -z ${_DEVICE_GRUB+x} ] && anstmp='/dev/sda' && _askno "Give a device for grub installation" "$(blkid -o device|grep -v '/loop'|xargs) ($anstmp)" && _DEVICE_GRUB=${_ANSWER:-$anstmp}
 _confset _DEVICE_GRUB "$_DEVICE_GRUB"
 
 _echoi "--------------------------"
-cat "${S_FILE_INSTALL_CONF}"
+cat "${_FILE_INSTALL_CONF}"
 _echoi "--------------------------"
 _askyn "PLease confirm installation" && [ "$_ANSWER" == n ] && exit 1
 
@@ -84,9 +135,8 @@ chown 1000.1000 -R "home/${_USERNAME}"
 # delete @home
 btrfs subvolume delete @home
 
-[ -d create ] && rm -fR create
-[ -d ubiquity-apt-clone ] && rm -fR ubiquity-apt-clone
-[ -d var ] && rm -fR var
+paths="create ubiquity-apt-clone var"
+for parh in $paths; do rm -fR "$path"; done
 
 _echoT "btrfs subvolume list $PWD"
 _echoi "$(btrfs subvolume list .)"
@@ -143,7 +193,7 @@ umount /mnt
 ########################################  END
 
 _echoT "------------------ write ${_PART}"
-_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"
+_partadd "${_PART}" "${_FILE_INSTALL_DONE}"
 
 _echoT "#################### END ${_PART}"
 
